In [2]:
import pandas as pd
df = pd.read_csv('data.csv', sep=',')
print(df.values)

[[1 'Sulfur dioxide' 'SO2' 'ppb' '1/10/2024 0:00' '0.6']
 [2 'Carbon monoxide' 'CO' 'ppm' '1/10/2024 0:00' '0.13']
 [3 'Ozone' 'O3' 'ppb' '1/10/2024 0:00' '24']
 ...
 [4 'PM10' 'PM10' 'μg/m3' '28/2/2025 23:00' '43']
 [3 'Ozone' 'O3' 'ppb' '28/2/2025 23:00' '0']
 [2 'Carbon monoxide' 'CO' 'ppm' '28/2/2025 23:00' '1.02']]

In [3]:
# printing data frame
print("Data frame")
print(df)

Data frame
       itemid         itemname itemengname itemunit      monitordate  \
0           1   Sulfur dioxide         SO2      ppb   1/10/2024 0:00
1           2  Carbon monoxide          CO      ppm   1/10/2024 0:00
2           3            Ozone          O3      ppb   1/10/2024 0:00
3           4             PM10        PM10    μg/m3   1/10/2024 0:00
4           5  Nitrogen oxides         NOx      ppb   1/10/2024 0:00
...       ...              ...         ...      ...              ...
65171       6     Nitric Oxide          NO      ppb  28/2/2025 23:00
65172       5  Nitrogen oxides         NOx      ppb  28/2/2025 23:00
65173       4             PM10        PM10    μg/m3  28/2/2025 23:00
65174       3            Ozone          O3      ppb  28/2/2025 23:00
65175       2  Carbon monoxide          CO      ppm  28/2/2025 23:00

      concentration
0               0.6
1              0.13
2                24
3                 4
4               4.9
...             ...
65171          12.9
65172          46.6
65173            43
65174             0
65175          1.02

[65176 rows x 6 columns]

In [4]:
# Get unique values of a column
print("Unique values of a column")
uniqueValues = df['itemname'].unique()
print(uniqueValues)

Unique values of a column
['Sulfur dioxide' 'Carbon monoxide' 'Ozone' 'PM10' 'Nitrogen oxides'
 'Nitric Oxide' 'Nitrogen dioxide' 'Total Hydrocarbon' 'Non-hydrocarbon'
 'Wind Speed' 'Wind Direction' 'Ambient temperature' 'Rainfall' 'Methane'
 'PM2.5' 'Relative humidity' 'Hourly Wind speed Vectors'
 'Hourly Wind Direction Vectors']

In [5]:
# Create dataframe with 'monitordate' and all the values in uniqueValues as header
print("Create dataframe with 'monitordate' and all the values in uniqueValues as header")
df2 = pd.DataFrame(columns = ['monitordate'])
for i in uniqueValues:
    df2[i] = 0
print(df2)

Create dataframe with 'monitordate' and all the values in uniqueValues as header
Empty DataFrame
Columns: [monitordate, Sulfur dioxide, Carbon monoxide, Ozone, PM10, Nitrogen oxides, Nitric Oxide, Nitrogen dioxide, Total Hydrocarbon, Non-hydrocarbon, Wind Speed, Wind Direction, Ambient temperature, Rainfall, Methane, PM2.5, Relative humidity, Hourly Wind speed Vectors, Hourly Wind Direction Vectors]
Index: []

In [17]:
import warnings
warnings.filterwarnings('ignore')

In [18]:
# Go through the original data frame and fill the new data frame
print("Go through the original data frame and fill the new data frame")
for index, row in df.iterrows():
    # print(row['monitordate'], row['itemname'], row['concentration'])
    # if monitordate not found in df2, add it
    if not df2['monitordate'].str.contains(row['monitordate']).any():
        # get df2 column count and create an empty array with 0
        empty_row = [0] * len(df2.columns)
        # add monitordate to the first element of the array
        empty_row[0] = row['monitordate']
        # add the array to the end of the dataframe
        df2.loc[len(df2)] = empty_row
    df2.loc[df2['monitordate'] == row['monitordate'], row['itemname']] = row['concentration']
print(df2)

Go through the original data frame and fill the new data frame
          monitordate Sulfur dioxide Carbon monoxide Ozone PM10  \
0      1/10/2024 0:00            0.6            0.13    24    4
1      1/10/2024 1:00              1            0.17  17.7    3
2      1/10/2024 2:00            1.3            0.23   9.6   15
3      1/10/2024 3:00            1.6            0.24  15.2   19
4      1/10/2024 4:00            1.4             0.2  14.2    8
...               ...            ...             ...   ...  ...
3616  28/2/2025 19:00            1.5            0.66    28   46
3617  28/2/2025 20:00            1.8             0.7    19   42
3618  28/2/2025 21:00            1.6            1.03     4   50
3619  28/2/2025 22:00            1.1            1.11     0   45
3620  28/2/2025 23:00            0.8            1.02     0   43

     Nitrogen oxides Nitric Oxide Nitrogen dioxide Total Hydrocarbon  \
0                4.9          0.3              4.5              1.91
1               12.4          0.6             11.7              1.97
2               16.1          0.5             15.5              2.09
3               12.6          0.2             12.4              2.13
4               11.6          0.1             11.5              2.16
...              ...          ...              ...               ...
3616            25.2          0.8               24              2.46
3617            31.6          0.9               30               2.6
3618            54.4         13.2               41              2.94
3619              55         13.8               41              3.06
3620            46.6         12.9               33               3.1

     Non-hydrocarbon Wind Speed Wind Direction Ambient temperature Rainfall  \
0               0.01        1.6             35                29.6        0
1               0.02        0.8            122                29.6        0
2               0.06        0.8             68                28.8        0
3               0.08        0.8             18                29.3        0
4                0.1        0.8            186                29.5        0
...              ...        ...            ...                 ...      ...
3616            0.22        0.5             35                21.8        0
3617            0.26        0.5            114                21.5        0
3618            0.38        0.3            133                20.7        0
3619            0.42        0.3            131                  20        0
3620            0.37        0.3             71                19.4        0

     Methane PM2.5 Relative humidity Hourly Wind speed Vectors  \
0        1.9     1                68                       1.6
1       1.95     0                69                       0.6
2       2.02     4                77                       0.8
3       2.04     7                75                       0.7
4       2.06     4                73                       0.4
...      ...   ...               ...                       ...
3616    2.24    36                73                       0.4
3617    2.34    38                75                       0.4
3618    2.56    41                80                       0.2
3619    2.64    40                84                       0.2
3620    2.73    33                87                       0.3

     Hourly Wind Direction Vectors
0                               50
1                               95
2                               69
3                               38
4                              153
...                            ...
3616                            36
3617                            62
3618                           104
3619                           117
3620                           136

[3621 rows x 19 columns]

In [19]:
df2

,monitordate,Sulfur dioxide,Carbon monoxide,Ozone,PM10,Nitrogen oxides,Nitric Oxide,Nitrogen dioxide,Total Hydrocarbon,Non-hydrocarbon,Wind Speed,Wind Direction,Ambient temperature,Rainfall,Methane,PM2.5,Relative humidity,Hourly Wind speed Vectors,Hourly Wind Direction Vectors
0,1/10/2024 0:00,0.6,0.13,24,4,4.9,0.3,4.5,1.91,0.01,1.6,35,29.6,0,1.9,1,68,1.6,50
1,1/10/2024 1:00,1,0.17,17.7,3,12.4,0.6,11.7,1.97,0.02,0.8,122,29.6,0,1.95,0,69,0.6,95
2,1/10/2024 2:00,1.3,0.23,9.6,15,16.1,0.5,15.5,2.09,0.06,0.8,68,28.8,0,2.02,4,77,0.8,69
3,1/10/2024 3:00,1.6,0.24,15.2,19,12.6,0.2,12.4,2.13,0.08,0.8,18,29.3,0,2.04,7,75,0.7,38
4,1/10/2024 4:00,1.4,0.2,14.2,8,11.6,0.1,11.5,2.16,0.1,0.8,186,29.5,0,2.06,4,73,0.4,153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3616,28/2/2025 19:00,1.5,0.66,28,46,25.2,0.8,24,2.46,0.22,0.5,35,21.8,0,2.24,36,73,0.4,36
3617,28/2/2025 20:00,1.8,0.7,19,42,31.6,0.9,30,2.6,0.26,0.5,114,21.5,0,2.34,38,75,0.4,62
3618,28/2/2025 21:00,1.6,1.03,4,50,54.4,13.2,41,2.94,0.38,0.3,133,20.7,0,2.56,41,80,0.2,104
3619,28/2/2025 22:00,1.1,1.11,0,45,55,13.8,41,3.06,0.42,0.3,131,20,0,2.64,40,84,0.2,117
3620,28/2/2025 23:00,0.8,1.02,0,43,46.6,12.9,33,3.1,0.37,0.3,71,19.4,0,2.73,33,87,0.3,136

In [20]:
# Filter rows where all columns except 'monitordate' are equal to 0
# df.loc[df2.drop(columns=['monitordate']).sum(axis=1) == 0]
mdf = df2.drop(columns=['monitordate'])
print("Change all datatype of float")
mdf = mdf.astype(float)
print("Add all values of a row")
print(mdf.sum(axis=1))

Change all datatype of float

ValueError: could not convert string to float: 'x'

In [21]:
print("Print row where 'x' appears as value in df2 in either columns")
print(df2.loc[df2.eq('x').any(axis=1)])
print("Get the index of the row where 'x' appears as value in df2 in either columns")
xIndex = df2.loc[df2.eq('x').any(axis=1)].index
print("Number of index")
print(len(xIndex))

Print row where 'x' appears as value in df2 in either columns
          monitordate Sulfur dioxide Carbon monoxide Ozone PM10  \
155   7/10/2024 11:00              x               x  21.5    x
156   7/10/2024 12:00            0.9            0.17     x   11
203   9/10/2024 11:00            1.5            0.23  48.4   21
204   9/10/2024 12:00            1.6            0.23  48.3   21
205   9/10/2024 13:00            1.5            0.23  46.3   22
...               ...            ...             ...   ...  ...
3523  24/2/2025 22:00            2.4            0.31    46   23
3559  26/2/2025 10:00              x               x    19   14
3560  26/2/2025 11:00              x               x     x   15
3561  26/2/2025 12:00            2.4            0.27     x    x
3599   28/2/2025 2:00            1.8            0.32    10   18

     Nitrogen oxides Nitric Oxide Nitrogen dioxide Total Hydrocarbon  \
155                x            x                x                 x
156              7.8          1.4              6.4              1.96
203              9.2          1.2                8                 x
204              9.5          1.1              8.3                 x
205             10.2            1              9.2                 x
...              ...          ...              ...               ...
3523             8.9          0.6                8              2.04
3559               x            x                x              2.16
3560               x            x                x                 x
3561            16.3          2.7               13              2.09
3599            12.6          0.8               11              2.17

     Non-hydrocarbon Wind Speed Wind Direction Ambient temperature Rainfall  \
155                x        2.4             40                29.3        x
156             0.06        2.9             24                29.8        x
203                x        4.3             32                26.7        0
204                x        4.4             29                26.4        0
205                x        3.2             34                26.1        0
...              ...        ...            ...                 ...      ...
3523            0.05        3.8             46                13.8        0
3559            0.11        1.8             35                16.3      0.5
3560               x        0.9             31                16.9        x
3561            0.09        2.6             33                17.8        x
3599            0.05        0.9             72                16.8        0

     Methane PM2.5 Relative humidity Hourly Wind speed Vectors  \
155        x     5                80                         2
156      1.9     x                78                       2.3
203        x     5                76                       3.2
204        x     8                76                       3.1
205        x    11                77                       2.7
...      ...   ...               ...                       ...
3523       2     x                74                       2.9
3559    2.04    17                99                       0.9
3560       x     x                98                       0.8
3561       2     7                92                       1.5
3599    2.12     x                88                       0.9

     Hourly Wind Direction Vectors
155                             37
156                             32
203                             31
204                             40
205                             37
...                            ...
3523                            47
3559                            36
3560                            41
3561                            35
3599                            77

[172 rows x 19 columns]
Get the index of the row where 'x' appears as value in df2 in either columns
Number of index
172

In [22]:
# df2 drop xIndex index
print("Drop xIndex index")
df2Modified = df2.drop(xIndex)
print(df2Modified)

Drop xIndex index
          monitordate Sulfur dioxide Carbon monoxide Ozone PM10  \
0      1/10/2024 0:00            0.6            0.13    24    4
1      1/10/2024 1:00              1            0.17  17.7    3
2      1/10/2024 2:00            1.3            0.23   9.6   15
3      1/10/2024 3:00            1.6            0.24  15.2   19
4      1/10/2024 4:00            1.4             0.2  14.2    8
...               ...            ...             ...   ...  ...
3616  28/2/2025 19:00            1.5            0.66    28   46
3617  28/2/2025 20:00            1.8             0.7    19   42
3618  28/2/2025 21:00            1.6            1.03     4   50
3619  28/2/2025 22:00            1.1            1.11     0   45
3620  28/2/2025 23:00            0.8            1.02     0   43

     Nitrogen oxides Nitric Oxide Nitrogen dioxide Total Hydrocarbon  \
0                4.9          0.3              4.5              1.91
1               12.4          0.6             11.7              1.97
2               16.1          0.5             15.5              2.09
3               12.6          0.2             12.4              2.13
4               11.6          0.1             11.5              2.16
...              ...          ...              ...               ...
3616            25.2          0.8               24              2.46
3617            31.6          0.9               30               2.6
3618            54.4         13.2               41              2.94
3619              55         13.8               41              3.06
3620            46.6         12.9               33               3.1

     Non-hydrocarbon Wind Speed Wind Direction Ambient temperature Rainfall  \
0               0.01        1.6             35                29.6        0
1               0.02        0.8            122                29.6        0
2               0.06        0.8             68                28.8        0
3               0.08        0.8             18                29.3        0
4                0.1        0.8            186                29.5        0
...              ...        ...            ...                 ...      ...
3616            0.22        0.5             35                21.8        0
3617            0.26        0.5            114                21.5        0
3618            0.38        0.3            133                20.7        0
3619            0.42        0.3            131                  20        0
3620            0.37        0.3             71                19.4        0

     Methane PM2.5 Relative humidity Hourly Wind speed Vectors  \
0        1.9     1                68                       1.6
1       1.95     0                69                       0.6
2       2.02     4                77                       0.8
3       2.04     7                75                       0.7
4       2.06     4                73                       0.4
...      ...   ...               ...                       ...
3616    2.24    36                73                       0.4
3617    2.34    38                75                       0.4
3618    2.56    41                80                       0.2
3619    2.64    40                84                       0.2
3620    2.73    33                87                       0.3

     Hourly Wind Direction Vectors
0                               50
1                               95
2                               69
3                               38
4                              153
...                            ...
3616                            36
3617                            62
3618                           104
3619                           117
3620                           136

[3449 rows x 19 columns]

In [23]:
mdf = df2Modified.drop(columns=['monitordate'])
mdf

,Sulfur dioxide,Carbon monoxide,Ozone,PM10,Nitrogen oxides,Nitric Oxide,Nitrogen dioxide,Total Hydrocarbon,Non-hydrocarbon,Wind Speed,Wind Direction,Ambient temperature,Rainfall,Methane,PM2.5,Relative humidity,Hourly Wind speed Vectors,Hourly Wind Direction Vectors
0,0.6,0.13,24,4,4.9,0.3,4.5,1.91,0.01,1.6,35,29.6,0,1.9,1,68,1.6,50
1,1,0.17,17.7,3,12.4,0.6,11.7,1.97,0.02,0.8,122,29.6,0,1.95,0,69,0.6,95
2,1.3,0.23,9.6,15,16.1,0.5,15.5,2.09,0.06,0.8,68,28.8,0,2.02,4,77,0.8,69
3,1.6,0.24,15.2,19,12.6,0.2,12.4,2.13,0.08,0.8,18,29.3,0,2.04,7,75,0.7,38
4,1.4,0.2,14.2,8,11.6,0.1,11.5,2.16,0.1,0.8,186,29.5,0,2.06,4,73,0.4,153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3616,1.5,0.66,28,46,25.2,0.8,24,2.46,0.22,0.5,35,21.8,0,2.24,36,73,0.4,36
3617,1.8,0.7,19,42,31.6,0.9,30,2.6,0.26,0.5,114,21.5,0,2.34,38,75,0.4,62
3618,1.6,1.03,4,50,54.4,13.2,41,2.94,0.38,0.3,133,20.7,0,2.56,41,80,0.2,104
3619,1.1,1.11,0,45,55,13.8,41,3.06,0.42,0.3,131,20,0,2.64,40,84,0.2,117
3620,0.8,1.02,0,43,46.6,12.9,33,3.1,0.37,0.3,71,19.4,0,2.73,33,87,0.3,136

In [25]:
print("Set all dtype to float")
mdf = mdf.astype(float)
mdf.sum(axis=1) == 0

Set all dtype to float

0       False
1       False
2       False
3       False
4       False
        ...
3616    False
3617    False
3618    False
3619    False
3620    False
Length: 3449, dtype: bool

In [31]:
print("Drop rows where all values equal 0")
mdf0 = mdf.loc[~(mdf.sum(axis=1) == 0)]
mdf0

Drop rows where all values equal 0

,Sulfur dioxide,Carbon monoxide,Ozone,PM10,Nitrogen oxides,Nitric Oxide,Nitrogen dioxide,Total Hydrocarbon,Non-hydrocarbon,Wind Speed,Wind Direction,Ambient temperature,Rainfall,Methane,PM2.5,Relative humidity,Hourly Wind speed Vectors,Hourly Wind Direction Vectors
0,0.6,0.13,24.0,4.0,4.9,0.3,4.5,1.91,0.01,1.6,35.0,29.6,0.0,1.90,1.0,68.0,1.6,50.0
1,1.0,0.17,17.7,3.0,12.4,0.6,11.7,1.97,0.02,0.8,122.0,29.6,0.0,1.95,0.0,69.0,0.6,95.0
2,1.3,0.23,9.6,15.0,16.1,0.5,15.5,2.09,0.06,0.8,68.0,28.8,0.0,2.02,4.0,77.0,0.8,69.0
3,1.6,0.24,15.2,19.0,12.6,0.2,12.4,2.13,0.08,0.8,18.0,29.3,0.0,2.04,7.0,75.0,0.7,38.0
4,1.4,0.20,14.2,8.0,11.6,0.1,11.5,2.16,0.10,0.8,186.0,29.5,0.0,2.06,4.0,73.0,0.4,153.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3616,1.5,0.66,28.0,46.0,25.2,0.8,24.0,2.46,0.22,0.5,35.0,21.8,0.0,2.24,36.0,73.0,0.4,36.0
3617,1.8,0.70,19.0,42.0,31.6,0.9,30.0,2.60,0.26,0.5,114.0,21.5,0.0,2.34,38.0,75.0,0.4,62.0
3618,1.6,1.03,4.0,50.0,54.4,13.2,41.0,2.94,0.38,0.3,133.0,20.7,0.0,2.56,41.0,80.0,0.2,104.0
3619,1.1,1.11,0.0,45.0,55.0,13.8,41.0,3.06,0.42,0.3,131.0,20.0,0.0,2.64,40.0,84.0,0.2,117.0
3620,0.8,1.02,0.0,43.0,46.6,12.9,33.0,3.10,0.37,0.3,71.0,19.4,0.0,2.73,33.0,87.0,0.3,136.0

In [33]:
print("Export mdf0 to csv as cleaned_data.csv without index")
mdf0.to_csv('cleaned_data.csv', index=False)

Export mdf0 to csv as cleaned_data.csv without index